version: "3.3"

services:
  namenode:
    image: apachehudi/hudi-hadoop_2.8.4-namenode:latest
    hostname: namenode
    container_name: namenode
    environment:
      - CLUSTER_NAME=hudi_example
    ports:
      - "50070:50070"
      - "8020:8020"
    env_file:
      - ./shared/config/hadoop.env
    volumes:
      - ./data:/data
    networks:
      - spark-network

  datanode:
    image: apachehudi/hudi-hadoop_2.8.4-datanode:latest
    container_name: datanode
    hostname: datanode
    environment:
      - CLUSTER_NAME=hudi_example
    env_file:
      - ./shared/config/hadoop.env
    ports:
      - "50075:50075"
      - "50010:50010"
    depends_on:
      - namenode
    networks:
      - spark-network

  historyserver:
    image: apachehudi/hudi-hadoop_2.8.4-history:latest
    hostname: historyserver
    container_name: historyserver
    environment:
      - CLUSTER_NAME=hudi_example
    depends_on:
      - "namenode"
    ports:
      - "58188:8188"
    env_file:
      - ./shared/config/hadoop.env
    volumes:
      - historyserver:/hadoop/yarn/timeline
    networks:
      - spark-network

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    volumes:
      - hive-metastore-postgresql:/var/lib/postgresql
    hostname: hive-metastore-postgresql
    container_name: hive-metastore-postgresql
    networks:
      - spark-network

  hivemetastore:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3:latest
    hostname: hivemetastore
    container_name: hivemetastore
    env_file:
      - ./shared/config/hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - "hive-metastore-postgresql"
      - "namenode"
    networks:
      - spark-network

  hiveserver:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3:latest
    hostname: hiveserver
    container_name: hiveserver
    env_file:
      - ./shared/config/hadoop.env
    environment:
      SERVICE_PRECONDITION: "hivemetastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - "hivemetastore"
    volumes:
      - ./shared:/var/hoodie/ws
    networks:
      - spark-network

  sparkmaster:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3-sparkmaster_2.4.4:latest
    hostname: sparkmaster
    container_name: sparkmaster
    env_file:
      - ./shared/config/hadoop.env
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-network

  spark-worker-1:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3-sparkworker_2.4.4:latest
    hostname: spark-worker-1
    container_name: spark-worker-1
    env_file:
      - ./shared/config/hadoop.env
    depends_on:
      - sparkmaster
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://sparkmaster:7077"
    networks:
      - spark-network

  adhoc-1:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3-sparkadhoc_2.4.4:latest
    hostname: adhoc-1
    container_name: adhoc-1
    env_file:
      - ./shared/config/hadoop.env
    depends_on:
      - sparkmaster
    ports:
      - "4040:4040"
    environment:
      - "SPARK_MASTER=spark://sparkmaster:7077"
    volumes:
      - ./shared:/var/hoodie/ws
    networks:
      - spark-network

volumes:
  namenode:
  datanode:
  historyserver:
  hive-metastore-postgresql:

networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
